public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getIncidentType() { return incidentType; }
    public void setIncidentType(String incidentType) { this.incidentType = incidentType; }

    public LocalTime getTimeOfIncident() { return timeOfIncident; }
    public void setTimeOfIncident(LocalTime timeOfIncident) { this.timeOfIncident = timeOfIncident; }

    public Integer getDateOfIncident() { return dateOfIncident; }
    public void setDateOfIncident(Integer dateOfIncident) { this.dateOfIncident = dateOfIncident; }

    public String getLocationOrZone() { return locationOrZone; }
    public void setLocationOrZone(String locationOrZone) { this.locationOrZone = locationOrZone; }

    public String getPersonsInvolved() { return personsInvolved; }
    public void setPersonsInvolved(String personsInvolved) { this.personsInvolved = personsInvolved; }

    public String getPersonsStatus() { return personsStatus; }
    public void setPersonsStatus(String personsStatus) { this.personsStatus = personsStatus; }

    public String getDescriptionOfIncident() { return descriptionOfIncident; }
    public void setDescriptionOfIncident(String descriptionOfIncident) { this.descriptionOfIncident = descriptionOfIncident; }

    public LocalDateTime getDateRecorded() { return dateRecorded; }
}
